In [2]:
import pandas as pd
import numpy as np
import os
import datetime
import matplotlib as mpl
import matplotlib.pyplot as plt

In [3]:
DATA_DIR = os.path.abspath('')
TARGET_DIR = os.path.dirname(DATA_DIR)+'/Columbia_clean'

In [7]:
for i in range(1,29):
    filename = '/Residential_'+str(i)+'.csv'
    temp = pd.read_csv(DATA_DIR+filename)
    print(filename)
    temp.index = pd.to_datetime(temp.date.astype(str) + ' ' + temp.hour.astype(str)+':00:00')
    temp = temp.drop(['date', 'hour'], axis=1)
    print(temp.columns)
    print(temp.isna().sum() / len(temp))
    #temp.to_csv(TARGET_DIR+filename, index=True)

/Residential_1.csv
Index(['energy_kWh'], dtype='object')
energy_kWh    0.0
dtype: float64
/Residential_2.csv
Index(['energy_kWh'], dtype='object')
energy_kWh    0.005688
dtype: float64
/Residential_3.csv
Index(['energy_kWh'], dtype='object')
energy_kWh    0.012891
dtype: float64
/Residential_4.csv
Index(['energy_kWh'], dtype='object')
energy_kWh    0.004714
dtype: float64
/Residential_5.csv
Index(['energy_kWh'], dtype='object')
energy_kWh    0.00517
dtype: float64
/Residential_6.csv
Index(['energy_kWh'], dtype='object')
energy_kWh    0.003117
dtype: float64
/Residential_7.csv
Index(['energy_kWh'], dtype='object')
energy_kWh    0.002818
dtype: float64
/Residential_8.csv
Index(['energy_kWh'], dtype='object')
energy_kWh    0.012698
dtype: float64
/Residential_9.csv
Index(['energy_kWh'], dtype='object')
energy_kWh    0.004418
dtype: float64
/Residential_10.csv
Index(['energy_kWh'], dtype='object')
energy_kWh    0.004714
dtype: float64
/Residential_11.csv
Index(['energy_kWh'], dtype='object')
energy_kWh    0.010455
dtype: float64
/Residential_12.csv
Index(['energy_kWh'], dtype='object')
energy_kWh    0.007755
dtype: float64
/Residential_13.csv
Index(['energy_kWh'], dtype='object')
energy_kWh    0.002091
dtype: float64
/Residential_14.csv
Index(['energy_kWh'], dtype='object')
energy_kWh    0.004752
dtype: float64
/Residential_15.csv
Index(['energy_kWh'], dtype='object')
energy_kWh    0.004946
dtype: float64
/Residential_16.csv
Index(['energy_kWh'], dtype='object')
energy_kWh    0.119386
dtype: float64
/Residential_17.csv
Index(['energy_kWh'], dtype='object')
energy_kWh    0.004129
dtype: float64
/Residential_18.csv
Index(['energy_kWh'], dtype='object')
energy_kWh    0.014028
dtype: float64
/Residential_19.csv
Index(['energy_kWh'], dtype='object')
energy_kWh    0.007489
dtype: float64
/Residential_20.csv
Index(['energy_kWh'], dtype='object')
energy_kWh    0.001968
dtype: float64
/Residential_21.csv
Index(['energy_kWh'], dtype='object')
energy_kWh    0.010563
dtype: float64
/Residential_22.csv
Index(['energy_kWh'], dtype='object')
energy_kWh    0.004008
dtype: float64
/Residential_23.csv
Index(['energy_kWh'], dtype='object')
energy_kWh    0.015159
dtype: float64
/Residential_24.csv
Index(['energy_kWh'], dtype='object')
energy_kWh    0.002281
dtype: float64
/Residential_25.csv
Index(['energy_kWh'], dtype='object')
energy_kWh    0.006235
dtype: float64
/Residential_26.csv
Index(['energy_kWh'], dtype='object')
energy_kWh    0.002874
dtype: float64
/Residential_27.csv
Index(['energy_kWh'], dtype='object')
energy_kWh    0.00264
dtype: float64
/Residential_28.csv
Index(['energy_kWh'], dtype='object')
energy_kWh    0.00228
dtype: float64

In [ ]:
for i in range(1,28):
    filename = '/Residential_'+str(i)+'.csv'
    temp = pd.read_csv(TARGET_DIR+filename, index_col=0)
    temp.index = pd.to_datetime(temp.index)
    years = temp.index.year.unique()
    # Prep Colors
    np.random.seed(100)
    mycolors = np.random.choice(list(mpl.colors.XKCD_COLORS.keys()), len(years), replace=False) 
    # Draw Plot
    fig, ax = plt.subplots(figsize=(16,12), dpi= 80)
    for d,year in enumerate(years):
            data_temp=temp.loc[temp.index.year==year, :]
            data_temp.plot(y='energy_kWh', use_index=True, color=mycolors[d], label = year, ax=ax, alpha=0.5)
    # Decoration
    plt.gca().set(ylabel='Consumption [kWh]', xlabel='# measurement')
    plt.yticks(fontsize=12, alpha=.7)
    plt.legend(fontsize=20)
    plt.title("Consumption in residential building "+str(i)+" by year", fontsize=20)
    plt.show()
    fig.savefig(TARGET_DIR+'/Residential_'+str(i)+'.png')   # save the figure to file
    plt.close(fig)

In [15]:
temp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29231 entries, 0 to 29230
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        29231 non-null  object
 1   hour        29231 non-null  int64
 2   energy_kWh  29231 non-null  float64
dtypes: float64(1), int64(1), object(1)
memory usage: 685.2+ KB

In [24]:
temp.index = pd.to_datetime(temp.date.astype(str) + ' ' + temp['hour'].astype(str)+':00:00')

In [26]:
temp.head(24)

                           date  hour  energy_kWh
2012-06-01 01:00:00  2012-06-01     1       1.011
2012-06-01 02:00:00  2012-06-01     2       0.451
2012-06-01 03:00:00  2012-06-01     3       0.505
2012-06-01 04:00:00  2012-06-01     4       0.441
2012-06-01 05:00:00  2012-06-01     5       0.468
2012-06-01 06:00:00  2012-06-01     6       0.451
2012-06-01 07:00:00  2012-06-01     7       0.464
2012-06-01 08:00:00  2012-06-01     8       0.897
2012-06-01 09:00:00  2012-06-01     9       1.066
2012-06-01 10:00:00  2012-06-01    10       0.946
2012-06-01 11:00:00  2012-06-01    11       0.465
2012-06-01 12:00:00  2012-06-01    12       0.792
2012-06-01 13:00:00  2012-06-01    13       0.468
2012-06-01 14:00:00  2012-06-01    14       0.674
2012-06-01 15:00:00  2012-06-01    15       0.503
2012-06-01 16:00:00  2012-06-01    16       0.556
2012-06-01 17:00:00  2012-06-01    17       0.925
2012-06-01 18:00:00  2012-06-01    18       0.713
2012-06-01 19:00:00  2012-06-01    19       0.597
2012-06-01 20:00:00  2012-06-01    20       0.559
2012-06-01 21:00:00  2012-06-01    21       0.752
2012-06-01 22:00:00  2012-06-01    22       1.584
2012-06-01 23:00:00  2012-06-01    23       4.188
2012-06-02 00:00:00  2012-06-02     0       0.613