In [7]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd

import os

In [2]:
houses = pd.read_csv('./informations_households.csv')

In [6]:
houses['LCLid'].nunique()

5566

In [5]:
houses

          LCLid stdorToU    Acorn Acorn_grouped       file
0     MAC005492      ToU   ACORN-        ACORN-    block_0
1     MAC001074      ToU   ACORN-        ACORN-    block_0
2     MAC000002      Std  ACORN-A      Affluent    block_0
3     MAC003613      Std  ACORN-A      Affluent    block_0
4     MAC003597      Std  ACORN-A      Affluent    block_0
...         ...      ...      ...           ...        ...
5561  MAC002056      Std  ACORN-U       ACORN-U  block_111
5562  MAC004587      Std  ACORN-U       ACORN-U  block_111
5563  MAC004828      Std  ACORN-U       ACORN-U  block_111
5564  MAC001704      ToU  ACORN-U       ACORN-U  block_111
5565  MAC002774      ToU  ACORN-U       ACORN-U  block_111

[5566 rows x 5 columns]

In [10]:
houses.Acorn.unique()

array(['ACORN-', 'ACORN-A', 'ACORN-B', 'ACORN-C', 'ACORN-D', 'ACORN-E',
       'ACORN-F', 'ACORN-G', 'ACORN-H', 'ACORN-I', 'ACORN-J', 'ACORN-K',
       'ACORN-L', 'ACORN-M', 'ACORN-N', 'ACORN-O', 'ACORN-P', 'ACORN-Q',
       'ACORN-U'], dtype=object)

In [9]:
halfhourly = pd.read_csv('./halfhourly_dataset/halfhourly_dataset/block_0.csv')
halfhourly

             LCLid                         tstp energy(kWh/hh)
0        MAC000002  2012-10-12 00:30:00.0000000             0
1        MAC000002  2012-10-12 01:00:00.0000000             0
2        MAC000002  2012-10-12 01:30:00.0000000             0
3        MAC000002  2012-10-12 02:00:00.0000000             0
4        MAC000002  2012-10-12 02:30:00.0000000             0
...            ...                          ...            ...
1222665  MAC005492  2014-02-27 22:00:00.0000000         0.182
1222666  MAC005492  2014-02-27 22:30:00.0000000         0.122
1222667  MAC005492  2014-02-27 23:00:00.0000000          0.14
1222668  MAC005492  2014-02-27 23:30:00.0000000         0.192
1222669  MAC005492  2014-02-28 00:00:00.0000000         0.088

[1222670 rows x 3 columns]

In [11]:
directory = './halfhourly_dataset/halfhourly_dataset/'
for filename in os.listdir(directory):
    if filename.endswith('.csv'):
        print(os.path.join(directory, filename))
        #halfhourly = pd.read_csv(filename)
        #halfhourly.LCLid.unique()
    else:
        continue

./halfhourly_dataset/halfhourly_dataset/block_71.csv
./halfhourly_dataset/halfhourly_dataset/block_65.csv
./halfhourly_dataset/halfhourly_dataset/block_59.csv
./halfhourly_dataset/halfhourly_dataset/block_58.csv
./halfhourly_dataset/halfhourly_dataset/block_64.csv
./halfhourly_dataset/halfhourly_dataset/block_70.csv
./halfhourly_dataset/halfhourly_dataset/block_99.csv
./halfhourly_dataset/halfhourly_dataset/block_66.csv
./halfhourly_dataset/halfhourly_dataset/block_72.csv
./halfhourly_dataset/halfhourly_dataset/block_73.csv
./halfhourly_dataset/halfhourly_dataset/block_67.csv
./halfhourly_dataset/halfhourly_dataset/block_98.csv
./halfhourly_dataset/halfhourly_dataset/block_88.csv
./halfhourly_dataset/halfhourly_dataset/block_63.csv
./halfhourly_dataset/halfhourly_dataset/block_77.csv
./halfhourly_dataset/halfhourly_dataset/block_76.csv
./halfhourly_dataset/halfhourly_dataset/block_62.csv
./halfhourly_dataset/halfhourly_dataset/block_89.csv
./halfhourly_dataset/halfhourly_dataset/block_48.csv
./halfhourly_dataset/halfhourly_dataset/block_74.csv
./halfhourly_dataset/halfhourly_dataset/block_60.csv
./halfhourly_dataset/halfhourly_dataset/block_61.csv
./halfhourly_dataset/halfhourly_dataset/block_75.csv
./halfhourly_dataset/halfhourly_dataset/block_49.csv
./halfhourly_dataset/halfhourly_dataset/block_108.csv
./halfhourly_dataset/halfhourly_dataset/block_12.csv
./halfhourly_dataset/halfhourly_dataset/block_4.csv
./halfhourly_dataset/halfhourly_dataset/block_5.csv
./halfhourly_dataset/halfhourly_dataset/block_13.csv
./halfhourly_dataset/halfhourly_dataset/block_109.csv
./halfhourly_dataset/halfhourly_dataset/block_11.csv
./halfhourly_dataset/halfhourly_dataset/block_39.csv
./halfhourly_dataset/halfhourly_dataset/block_7.csv
./halfhourly_dataset/halfhourly_dataset/block_6.csv
./halfhourly_dataset/halfhourly_dataset/block_38.csv
./halfhourly_dataset/halfhourly_dataset/block_10.csv
./halfhourly_dataset/halfhourly_dataset/block_28.csv
./halfhourly_dataset/halfhourly_dataset/block_14.csv
./halfhourly_dataset/halfhourly_dataset/block_2.csv
./halfhourly_dataset/halfhourly_dataset/block_3.csv
./halfhourly_dataset/halfhourly_dataset/block_15.csv
./halfhourly_dataset/halfhourly_dataset/block_29.csv
./halfhourly_dataset/halfhourly_dataset/block_17.csv
./halfhourly_dataset/halfhourly_dataset/block_1.csv
./halfhourly_dataset/halfhourly_dataset/block_0.csv
./halfhourly_dataset/halfhourly_dataset/block_16.csv
./halfhourly_dataset/halfhourly_dataset/block_101.csv
./halfhourly_dataset/halfhourly_dataset/block_33.csv
./halfhourly_dataset/halfhourly_dataset/block_27.csv
./halfhourly_dataset/halfhourly_dataset/block_26.csv
./halfhourly_dataset/halfhourly_dataset/block_32.csv
./halfhourly_dataset/halfhourly_dataset/block_100.csv
./halfhourly_dataset/halfhourly_dataset/block_102.csv
./halfhourly_dataset/halfhourly_dataset/block_24.csv
./halfhourly_dataset/halfhourly_dataset/block_30.csv
./halfhourly_dataset/halfhourly_dataset/block_18.csv
./halfhourly_dataset/halfhourly_dataset/block_19.csv
./halfhourly_dataset/halfhourly_dataset/block_31.csv
./halfhourly_dataset/halfhourly_dataset/block_25.csv
./halfhourly_dataset/halfhourly_dataset/block_103.csv
./halfhourly_dataset/halfhourly_dataset/block_107.csv
./halfhourly_dataset/halfhourly_dataset/block_21.csv
./halfhourly_dataset/halfhourly_dataset/block_35.csv
./halfhourly_dataset/halfhourly_dataset/block_34.csv
./halfhourly_dataset/halfhourly_dataset/block_20.csv
./halfhourly_dataset/halfhourly_dataset/block_106.csv
./halfhourly_dataset/halfhourly_dataset/block_110.csv
./halfhourly_dataset/halfhourly_dataset/block_104.csv
./halfhourly_dataset/halfhourly_dataset/block_36.csv
./halfhourly_dataset/halfhourly_dataset/block_22.csv
./halfhourly_dataset/halfhourly_dataset/block_8.csv
./halfhourly_dataset/halfhourly_dataset/block_9.csv
./halfhourly_dataset/halfhourly_dataset/block_23.csv
./halfhourly_dataset/halfhourly_dataset/block_37.csv
./halfhourly_dataset/halfhourly_dataset/block_105.csv
./halfhourly_dataset/halfhourly_dataset/block_111.csv
./halfhourly_dataset/halfhourly_dataset/block_93.csv
./halfhourly_dataset/halfhourly_dataset/block_87.csv
./halfhourly_dataset/halfhourly_dataset/block_50.csv
./halfhourly_dataset/halfhourly_dataset/block_44.csv
./halfhourly_dataset/halfhourly_dataset/block_78.csv
./halfhourly_dataset/halfhourly_dataset/block_79.csv
./halfhourly_dataset/halfhourly_dataset/block_45.csv
./halfhourly_dataset/halfhourly_dataset/block_51.csv
./halfhourly_dataset/halfhourly_dataset/block_86.csv
./halfhourly_dataset/halfhourly_dataset/block_92.csv
./halfhourly_dataset/halfhourly_dataset/block_84.csv
./halfhourly_dataset/halfhourly_dataset/block_90.csv
./halfhourly_dataset/halfhourly_dataset/block_47.csv
./halfhourly_dataset/halfhourly_dataset/block_53.csv
./halfhourly_dataset/halfhourly_dataset/block_52.csv
./halfhourly_dataset/halfhourly_dataset/block_46.csv
./halfhourly_dataset/halfhourly_dataset/block_91.csv
./halfhourly_dataset/halfhourly_dataset/block_85.csv
./halfhourly_dataset/halfhourly_dataset/block_81.csv
./halfhourly_dataset/halfhourly_dataset/block_95.csv
./halfhourly_dataset/halfhourly_dataset/block_42.csv
./halfhourly_dataset/halfhourly_dataset/block_56.csv
./halfhourly_dataset/halfhourly_dataset/block_57.csv
./halfhourly_dataset/halfhourly_dataset/block_43.csv
./halfhourly_dataset/halfhourly_dataset/block_94.csv
./halfhourly_dataset/halfhourly_dataset/block_80.csv
./halfhourly_dataset/halfhourly_dataset/block_96.csv
./halfhourly_dataset/halfhourly_dataset/block_82.csv
./halfhourly_dataset/halfhourly_dataset/block_69.csv
./halfhourly_dataset/halfhourly_dataset/block_55.csv
./halfhourly_dataset/halfhourly_dataset/block_41.csv
./halfhourly_dataset/halfhourly_dataset/block_40.csv
./halfhourly_dataset/halfhourly_dataset/block_54.csv
./halfhourly_dataset/halfhourly_dataset/block_68.csv
./halfhourly_dataset/halfhourly_dataset/block_83.csv
./halfhourly_dataset/halfhourly_dataset/block_97.csv